// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkLZZ38UrnTpGbuxzZvA3H8zyzAvTXEwQ',
    appId: '1:160658128773:web:e26ee665badddba7548eec',
    messagingSenderId: '160658128773',
    projectId: 'talky-flutter-ccdba',
    authDomain: 'talky-flutter-ccdba.firebaseapp.com',
    storageBucket: 'talky-flutter-ccdba.firebasestorage.app',
    measurementId: 'G-51SDFB32PB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz7xWoc412T0IRIxwn-Cwd6HcAopwJ5so',
    appId: '1:160658128773:android:77f7b5495a87957b548eec',
    messagingSenderId: '160658128773',
    projectId: 'talky-flutter-ccdba',
    storageBucket: 'talky-flutter-ccdba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMns0qg6wYC2jCl1QclBR1k4DJDZ8YEGM',
    appId: '1:160658128773:ios:a557a3e1e12b3ad8548eec',
    messagingSenderId: '160658128773',
    projectId: 'talky-flutter-ccdba',
    storageBucket: 'talky-flutter-ccdba.firebasestorage.app',
    iosBundleId: 'com.example.flutterProjects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMns0qg6wYC2jCl1QclBR1k4DJDZ8YEGM',
    appId: '1:160658128773:ios:a557a3e1e12b3ad8548eec',
    messagingSenderId: '160658128773',
    projectId: 'talky-flutter-ccdba',
    storageBucket: 'talky-flutter-ccdba.firebasestorage.app',
    iosBundleId: 'com.example.flutterProjects',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkLZZ38UrnTpGbuxzZvA3H8zyzAvTXEwQ',
    appId: '1:160658128773:web:178db375076b421f548eec',
    messagingSenderId: '160658128773',
    projectId: 'talky-flutter-ccdba',
    authDomain: 'talky-flutter-ccdba.firebaseapp.com',
    storageBucket: 'talky-flutter-ccdba.firebasestorage.app',
    measurementId: 'G-JSQJ2LNCKE',
  );
}
