name: talky
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_lints: ^5.0.0
  curved_navigation_bar: ^1.0.6
  google_fonts: ^6.2.1
  get: ^4.6.5
  fl_country_code_picker: ^0.1.9+1
  pinput: ^5.0.1
  lottie: ^3.3.1
  image_picker: ^1.0.7
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  cloud_firestore: ^5.0.1
  firebase_storage: ^12.0.0
  flutter_contacts: ^1.1.6
  permission_handler: ^12.0.0+1
  shared_preferences: ^2.2.2
  intl: 0.19.0
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.0.0
  image: ^4.0.17
  path_provider: ^2.1.2
  chat_bubbles: ^1.3.2
  emoji_picker_flutter: ^4.3.0
  cached_network_image: ^3.2.3
  firebase_database: ^11.3.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

flutter_icons:
  android: true
  ios: true
